### ISSUE TITLE
Support -x option

### ISSUE THREAD

**Issue by oric01** [jscs-dev/grunt-jscs#83] opened 2015-04-01 15:09 UTC
Hi,

As explained in https://medium.com/@addyosmani/auto-formatting-javascript-code-style-fe0f98a923b8#1e26 , could you support  `jscs myfile.js -x` which will reformat code according the .jscsrc config  

Thx !

**Comment by gustavohenke** [comment] 2015-04-01 17:14
Duplicate of #82.

**Closed by gustavohenke** 2015-04-01 17:14 UTC
